qlib_init:
    provider_uri: "/home/qdata/qlib_data/custom_cn_data"
    region: cn
market: &market test_100
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2021-12-31
    fit_start_time: 2008-01-01
    fit_end_time: 2021-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              # col_list: &col_list ["STD5", "TURNOVER_CLOSE", "TMA5","TSUMP5", "CORR5","RESI10","ROC60","CORR20","KSFT","KLOW"]  
              col_list: &col_list ['STD5', 'TURNOVER_CLOSE','PRICE_SCOPE', 'CORR5','RESI10']                 
    learn_processors:
        - class: DropnaLabel
    # label: ["Ref($close, -1)"] 
    label: ["$close / Ref($close, 1) - 1"] 
    # label: ["$volume/100"]

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal:
                - <MODEL> 
                - <DATASET>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2017-01-01
        end_time: 2020-08-01
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: TftDataframeModel
        module_path: darts_pro.tft_process_dataframe
        kwargs:
            GPU: 0
            batch_size: 128
            seed: 0
            n_jobs: 20
            type: 'predict'
            n_epochs : 300
            optargs:
               data_type: 'combine'
               data_path: 'custom/data/aug/darts/all_nor.npy'
               work_dir: 'custom/data/darts'
               model_name: 'test8_tft_100'
               load_weight: True
               wave_period : &wave_period 30
               forecast_horizon: &forecast_horizon 5
    dataset:
        class: TFTSeriesDataset
        module_path: darts_pro.tft_series_dataset
        kwargs:
            handler:
                class: TftDataHandler
                module_path: tft.tft_handler
                kwargs: *data_handler_config
            segments:
                train_total: [2010-01-01, 2021-03-01]
                valid: [2020-12-01, 2021-03-01]
                test: [2021-01-01, 2021-03-01]
            data_path: 'custom/data/aug/darts/all_nor.npy'
            aug_type: 'no'
            data_type: 'date_range'
            instrument_pick: [600025,600031,600010,600011,600012,600010,600015,600016,600017]
            scaler_type: 'norm'
            model_type: 'tft'
            step_len: *wave_period
            pred_len: *forecast_horizon
            over_time: 2          
            low_threhold: -5
            high_threhold: 5   
            col_def:
                col_list: *col_list
                group_column: 'instrument'
                datetime_index_column: 'datetime_number'
                group_rank_column: 'instrument_rank'
                target_column: 'label'
                time_column: 'time_idx'    
                future_covariate_col: ['dayofweek']   
                past_covariate_col: ['STD5','PRICE_SCOPE','TURNOVER_CLOSE', 'CORR5','RESI10']  
                static_covariate_col: ['instrument']    
                
    record: 
        - class: SignalRecord
          module_path: trader.tft_recorder
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>    
        - class: SigAnaRecord
          module_path: trader.tft_recorder
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
