benchmark: SH000300
data_handler_config: &id002
  end_date: '2023-04-26'
  end_time: 2023-12-31
  fit_end_time: 2023-12-31
  fit_start_time: 2008-01-01
  infer_processors:
  - class: FilterCol
    kwargs:
      col_list: &id001
      - STD5
      - TURNOVER_CLOSE
      - PRICE_SCOPE
      - CORR5
      - RESI10
      - CLOSE
      - OPEN
      - HIGH
      - LOW
      - VOLUME_CLOSE
      - RSI20
      - MACD
      fields_group: feature
  instruments: test_100
  label:
  - $close
  learn_processors:
  - class: DropnaLabel
  start_date: '2008-01-01'
  start_time: 2008-01-01
market: test_100
port_analysis_config: &id003
  backtest:
    account: 100000000
    benchmark: SH000300
    build_data: true
    exchange_kwargs:
      close_cost: 0.0015
      deal_price: close
      limit_threshold: 0.095
      min_cost: 5
      open_cost: 0.0005
    pred_end_time: 2023-05-05 00:00:00
    pred_start_time: 2023-04-26 00:00:00
    work_dir: custom/data/rl
  strategy:
    class: RLStrategy
    kwargs:
      dataset: <DATASET>
      model: <MODEL>
      topk: 3
    module_path: custom.trader.rl_strategy
qlib_init:
  provider_uri: /home/qdata/qlib_data/custom_cn_data
  region: cn
task:
  dataset:
    class: TFTSeriesDataset
    kwargs:
      aug_type: 'no'
      col_def:
        col_list: *id001
        datetime_index_column: datetime_number
        future_covariate_col:
        - dayofweek
        - month
        group_column: instrument
        group_rank_column: instrument_rank
        past_covariate_col:
        - STD5
        - PRICE_SCOPE
        - TURNOVER_CLOSE
        - CORR5
        - RESI10
        static_covariate_col:
        - industry
        - tradable_shares
        target_column: label
        time_column: time_idx
      data_path: custom/data/aug/darts/all_nor.npy
      data_type: date_range
      handler:
        class: TftDataHandler
        kwargs: *id002
        module_path: tft.tft_handler
      high_threhold: 5
      instrument_pick:
      - 600520
      - 600521
      - 600522
      load_dataset_file: False
      low_threhold: -5
      model_type: tft
      over_time: 2
      pred_len: 5
      scaler_type: norm
      segments:
        test:
        - 2021-01-01
        - 2021-03-01
        train_total:
        - '2008-01-01'
        - '2023-04-26'
        valid:
        - 2022-12-12
        - 2023-03-14
      step_len: 30
    module_path: darts_pro.tft_series_dataset
  model:
    class: TftDataframeModel
    kwargs:
      GPU: 0
      batch_size: 1024
      load_dataset_file: False
      n_epochs: 300
      n_jobs: 20
      optargs:
        data_path: custom/data/aug/darts/all_nor.npy
        data_type: combine
        forecast_horizon: 5
        load_weight: true
        model_name: train_202304
        wave_period: 30
        work_dir: /home/qdata/workflow/wf_backtest_flow_2023/task/118/model
      pred_data_file: pred_df_total.pkl
      pred_data_path: /home/qdata/workflow/wf_backtest_flow_2023/task/118/dump_data
      save_dataset_file: False
      seed: 0
      type: build_pred_result
    module_path: darts_pro.tft_process_dataframe
  record:
  - class: PortAnaRecord
    kwargs:
      config: *id003
      dataset: <DATASET>
      model: <MODEL>
      pred_data_file: pred_df_total.pkl
      pred_data_path: /home/qdata/workflow/wf_backtest_flow_2023/task/118/dump_data
    module_path: trader.pred_recorder
