qlib_init:
    provider_uri: '/home/qdata/qlib_data/custom_cn_data'
    region: cn
market: &market test_5
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    init_data: True
    start_time: 2008-01-01
    end_time: 2023-12-31
    fit_start_time: 2008-01-01
    fit_end_time: 2023-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              # col_list: &col_list ['STD5', 'TURNOVER_CLOSE', 'TMA5','TSUMP5', 'CORR5','RESI10','ROC60','CORR20','KSFT','KLOW']  
              col_list: &col_list ['MACD','RSI5','RSI20','OBV5','label_ori','label_norm','VOLUME_CLOSE','WVMA5','BETA5','RSQR5',
              'RESI5','CLOSE','OPEN','HIGH', 'LOW','RSI10','KDJ_K','KDJ_D','KDJ_J','CCI5','ATR5','AOS','HIGH_QTLU5','RVI',
              "KMID","KLEN","KMID2","KUP","KUP2","KLOW","KLOW2","KSFT","KSFT2", 'STD5','MA5','QTLU5','CORD5','CNTD5','VSTD5','IMAX5','IMIN5','QTLUMA5',
              'KURT5','SKEW5','CNTP5','CNTN5','SUMP5','CORR5','RANK5','RANKMA5','DIFF','DEA','SUMPMA5']                                   
    learn_processors:
        - class: DropnaLabel
    # label: ['Ref($close, -1)'] 
    label: ['$close'] 
    # label: ['$volume/100']

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal:
                - <MODEL> 
                - <DATASET>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2017-01-01
        end_time: 2020-08-01
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: TftDataframeModel
        module_path: darts_pro.tft_process_dataframe
        kwargs:
            GPU: 0
            batch_size: 16
            seed: 0
            n_jobs: 20
            log_every_n_steps: 50
            type: 'pred_industry_roll'
            n_epochs : 180
            save_dataset_file: False
            load_dataset_file: &load_dataset_file True
            batch_file_path: 'custom/data/asis/Industry_COMBINE_INDEX_202202'
            pred_data_path: "/home/qdata/workflow/wf_backtest_flow_2023/task/118/dump_data/"   
            scheduler_config: 
               start_factor: 1
               end_factor: 0.05
               total_iters: 2e4
               # base_lr: 0.5e-4
               # max_lr: 1.5e-3
               # cycle_momentum: False
               # step_size_up: 100000
               # T_max: 5
               # eta_min: 0.001
            optimizer_kwargs:
               lr: 1e-3
               weight_decay: 1e-4
            optargs:
               data_type: 'combine'
               data_path: 'custom/data/aug/darts/all_nor.npy'
               work_dir: 'custom/data/darts'
               model_name: "Industry_TimeMix_COMBINE_NOCORR_202201"
               model_type: 'mlp'
               load_weight: True
               best_weight: False
               step_mode: 'complete'
               pretrain_model_name: 'MLP_PRETRAIN_1000_202110'
               wave_period : &wave_period 30
               hidden_size: 32
               forecast_horizon: &forecast_horizon 5
               dropout: 0.5 
               past_split: [[0,12],[12,24]]
               filter_conv_index: -1
    dataset:
        class: TFTSeriesDataset
        module_path: darts_pro.tft_series_dataset
        kwargs:
            handler:
                class: TftDataHandler
                module_path: tft.tft_handler
                kwargs: *data_handler_config
            segments:
                train: [2010-01-01, 2022-02-28]
                valid: [2022-01-31, 2022-05-31]
                test: [2021-01-01, 2021-03-01]
            whole_data: False
            data_path: 'custom/data/aug/darts/all_nor.npy'
            load_dataset_file: *load_dataset_file
            aug_type: 'no'
            data_type: 'date_range'
            transform_inner: True
            scale_time_col: False
            instrument_pick: [600520,600521,600522]
            scaler_type: 'norm'
            model_type: 'tft'
            step_len: *wave_period
            pred_len: *forecast_horizon
            over_time: 2          
            low_threhold: -5
            high_threhold: 5   
            col_def:
                col_list: *col_list
                group_column: 'instrument'
                datetime_index_column: 'datetime_number'
                group_rank_column: 'instrument_rank'
                target_column: ['QTLUMA5','RVI','label_norm']
                time_column: 'time_idx'    
                future_covariate_col: ['dayofweek','month']   
                past_covariate_col: ['KMID','MACD','RSI5','OBV5','WVMA5','BETA5','OPEN','HIGH', 'LOW','CCI5','ATR5','AOS'
                                  ,'KMID','MACD','RSI5','OBV5','WVMA5','BETA5','OPEN','HIGH', 'LOW','CCI5','ATR5','AOS'
                                  ,'KMID','MACD','RSI5','OBV5','WVMA5','BETA5','OPEN','HIGH', 'LOW','CCI5','ATR5','AOS'
                                  ] 
                static_covariate_col: ['cons_num','static_pe','yield']    
