qlib_init:
    provider_uri: "/home/qdata/qlib_data/custom_cn_data"
    region: cn
market: &market all
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    init_data: True
    start_time: 2022-01-01
    end_time: 2023-12-31
    fit_start_time: 2022-01-01
    fit_end_time: 2023-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              # col_list: &col_list ["STD5", "TURNOVER_CLOSE", "TMA5","TSUMP5", "CORR5","RESI10","ROC60","CORR20","KSFT","KLOW"]  
              col_list: &col_list ['STD5', 'TURNOVER_CLOSE','PRICE_SCOPE', 'CORR5','RESI10','CLOSE','OPEN','HIGH', 'LOW','VOLUME_CLOSE','RSI20','MACD']                  
    learn_processors:
        - class: DropnaLabel
    # label: ["Ref($close, -1)"] 
    label: ["$close"] 
    # label: ["$volume/100"]

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal:
                - <MODEL> 
                - <DATASET>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2020-11-16
        end_time: 2021-01-31
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: TftDataframeModel
        module_path: darts_pro.tft_process_dataframe
        kwargs:
            GPU: 0
            batch_size: 1024
            seed: 0
            n_jobs: 20
            type: 'predict'
            n_epochs : 300
            save_dataset_file: False  
            load_dataset_file: &load_dataset_file False     
            pred_data_path: "custom/data/darts/dump_data"     
            optargs:
               data_type: 'combine'
               data_path: 'custom/data/aug/darts/all_nor.npy'
               work_dir: 'custom/data/darts'
               model_name: 'test9_tft_all_step5'
               load_weight: True
               wave_period : &wave_period 30
               forecast_horizon: &forecast_horizon 5
    dataset:
        class: TFTSeriesDataset
        module_path: darts_pro.tft_series_dataset
        kwargs:
            handler:
                class: TftDataHandler
                module_path: tft.tft_handler
                kwargs: *data_handler_config
            segments:
                train_total: [2022-01-01, 2023-05-31]
                valid: [2022-10-01, 2023-03-31]
                test: [2021-01-01, 2021-03-01]
            data_path: 'custom/data/aug/darts/all_nor.npy'
            load_dataset_file: *load_dataset_file
            aug_type: 'no'
            data_type: 'date_range'
            # instrument_pick: [428,429,504]
            instrument_pick: []
            scaler_type: 'norm'
            model_type: 'tft'
            step_len: *wave_period
            pred_len: *forecast_horizon
            over_time: 2          
            low_threhold: -5
            high_threhold: 5   
            col_def:
                col_list: *col_list
                group_column: 'instrument'
                datetime_index_column: 'datetime_number'
                group_rank_column: 'instrument_rank'
                target_column: 'label'
                time_column: 'time_idx'    
                future_covariate_col: ['dayofweek','month']   
                past_covariate_col: ['STD5','PRICE_SCOPE','TURNOVER_CLOSE', 'CORR5','RESI10']  
                static_covariate_col: ['industry','tradable_shares']  
                
    record: 
        - class: SignalRecord
          module_path: trader.tft_recorder
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>    
        - class: SigAnaRecord
          module_path: trader.tft_recorder
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
