qlib_init:
    provider_uri: "/home/qdata/qlib_data/custom_cn_data"
    region: cn
market: &market all
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2021-12-31
    fit_start_time: 2008-01-01
    fit_end_time: 2021-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              col_list: &col_list ["STD5", "TURNOVER_CLOSE","TMA5", "TSUMP5", "CORR5","RESI10","ROC60","CORR20","KSFT","PRICE_SCOPE"]                
    learn_processors:
        - class: DropnaLabel
    # label: ["Ref($close, -1)"] 
    label: ["$close / Ref($close, 1) - 1"] 
    # label: ["$volume/100"]

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal:
                - <MODEL> 
                - <DATASET>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2017-01-01
        end_time: 2020-08-01
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: TftNumpyModel
        module_path: darts_pro.tft_process
        kwargs:
            GPU: 0
            batch_size: 8
            seed: 0
            n_jobs: 20
            type: 'data_aug'
            optargs:
               aug_type: 'combine'
               wave_period : 30
               forecast_horizon: 1
               wave_threhold: -10
               wave_window: 5
               over_time: 1
               wave_threhold_type: 'more'
               save_path: 'custom/data/aug/darts/all_nor.npy'
               log_path: 'custom/data/lightning_logs'
    dataset:
        class: TFTDataset
        module_path: darts_pro.tft_dataset
        kwargs:
            handler:
                class: TftDataHandler
                module_path: tft.tft_handler
                kwargs: *data_handler_config
            segments:
                train: [2008-01-01, 2020-12-31]
                valid: [2015-01-01, 2020-12-31]
                test: [2017-01-01, 2020-08-01]
            step_len: 30
            pred_len: 5   
            col_def:
                col_list: *col_list
                group_column: 'instrument'
                target_column: 'label'
                time_column: 'time_idx'
                future_covariate_col: ['dayofweek']   
                past_covariate_col: *col_list
                
