qlib_init:
    provider_uri: "/home/qdata/qlib_data/custom_cn_data"
    region: cn
market: &market test_one
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2020-08-01
    fit_start_time: 2008-01-01
    fit_end_time: 2014-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              col_list: &col_list ["STD5", "VSTD5"]                
    learn_processors:
        - class: DropnaLabel
    # label: ["Ref($close, -1)"] 
    label: ["$close / Ref($close, 1) - 1"] 
    # label: ["$volume/100"]

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal:
                - <MODEL> 
                - <DATASET>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2017-01-01
        end_time: 2020-08-01
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: TftNumpyModel
        module_path: darts_pro.tft_numpy
        kwargs:
            GPU: 0
            batch_size: 8
            seed: 0
            n_jobs: 20
            type: 'data_view'
            optargs:
               aug_type: 'combine'
               data_path: 'custom/data/aug/darts/all_nor.npy'
               wave_period : 30
               forecast_horizon: 5
               low_threhold: -5
               high_threhold: 5
               over_time: 2                           
    dataset:
        class: TFTDataset
        module_path: darts_pro.tft_dataset
        kwargs:
            handler:
                class: TftDataHandler
                module_path: tft.tft_handler
                kwargs: *data_handler_config
            segments:
                train: [2008-01-01, 2020-12-31]
                valid: [2015-01-01, 2020-12-31]
                test: [2017-01-01, 2020-08-01]
            step_len: 30
            pred_len: 5   
            col_def:
                col_list: *col_list
                group_column: 'instrument'
                target_column: 'label'
                time_column: 'time_idx'
                covariate_columns: ['dayofweek'] 
