qlib_init:
    provider_uri: "/home/qdata/qlib_data/custom_cn_data"
    region: cn
market: &market test_5
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2020-12-31
    fit_start_time: 2008-01-01
    fit_end_time: 2020-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              col_list: &col_list ['Year','Month']        
    learn_processors:
        - class: DropnaLabel
    # label: ["Ref($close, -1)"] 
    label: ["$close / Ref($close, 1) - 1"] 
    # label: ["$volume/100"]

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal:
                - <MODEL> 
                - <DATASET>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2017-01-01
        end_time: 2020-08-01
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: TftNumpyModel
        module_path: darts_pro.tft_process
        kwargs:
            GPU: 0
            batch_size: 4096
            seed: 0
            n_jobs: 20
            type: 'train'
            n_epochs : 300
            optargs:
               work_dir: 'custom/data/darts'
               model_name: 'test6_tft_air'
               load_weight: False
               wave_period : &wave_period 16
               forecast_horizon: &forecast_horizon 1
    dataset:
        class: TFTNumpyDataset
        module_path: darts_pro.tft_numpy_dataset
        kwargs:
            handler:
                class: TftDataHandler
                module_path: tft.tft_handler
                kwargs: *data_handler_config
            segments:
                train: [2010-01-01, 2020-08-31]
                valid: [2020-09-01, 2020-10-15]
                test: [2017-01-01, 2020-08-01]
            data_path: 'custom/data/aug/tests/air.npy'
            data_type: 'combine'
            # instrument_pick: [600520,600521]
            aug_type: 'no'
            scaler_type: 'norm'
            model_type: 'tft'
            step_len: *wave_period
            pred_len: *forecast_horizon
            over_time: 2         
            low_threhold: -5
            high_threhold: 5   
            col_def:
                col_list: *col_list
                group_column: 'instrument'
                target_column: 'label'
                time_column: 'time_idx'    
                future_covariate_col: ['Year','Month']   
                past_covariate_col: []    
                static_covariate_col: []    

    record: 
        - class: TftRecord
          module_path: tft.tft_recorder
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
