qlib_init:
    provider_uri: "/home/qdata/qlib_data/custom_cn_data"
    region: cn
market: &market all
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2022-12-31
    fit_start_time: 2008-01-01
    fit_end_time: 2022-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              # col_list: &col_list ["STD5", "TURNOVER_CLOSE", "TMA5","TSUMP5", "CORR5","RESI10","ROC60","CORR20","KSFT","KLOW"]  
              col_list: &col_list ['STD5', 'TURNOVER_CLOSE','PRICE_SCOPE', 'CORR5','RESI10','CLOSE','OPEN','HIGH', 'LOW','VOLUME_CLOSE','RSI20','MACD']                 
    learn_processors:
        - class: DropnaLabel
    # label: ["Ref($close, -1)"] 
    label: ["$close"] 
    # label: ["$volume/100"]

task:
    model:
        class: TftDataframeModel
        module_path: darts_pro.tft_process_dataframe
        kwargs:
            GPU: 0
            batch_size: 128
            seed: 0
            n_jobs: 20
            type: 'classify_train'
            n_epochs : 300
            save_dataset_file: False
            load_dataset_file: &load_dataset_file True
            pred_data_path: "custom/data/darts/dump_data/test7_0501"
            optargs:
               data_type: 'combine'
               data_path: 'custom/data/aug/darts/all_nor.npy'
               work_dir: 'custom/data/darts'
               model_name: 'test7_tft_all_step5'
               load_weight: True
               wave_period : &wave_period 30
               forecast_horizon: &forecast_horizon 5
    dataset:
        class: TFTSeriesDataset
        module_path: darts_pro.tft_series_dataset
        kwargs:
            handler:
                class: TftDataHandler
                module_path: tft.tft_handler
                kwargs: *data_handler_config
            segments:
                train_total: [2010-01-01, 2022-12-31]
                valid: [2021-02-01, 2021-03-31]
                test: [2021-01-01, 2021-03-01]         
                classify_range: [2021-01-01, 2021-02-01]
            data_path: 'custom/data/aug/darts/all_nor.npy'
            load_dataset_file: *load_dataset_file
            aug_type: 'no'
            data_type: 'date_range'
            instrument_pick: [603986,603980,603987]
            scaler_type: 'norm'
            model_type: 'tft'
            step_len: *wave_period
            pred_len: *forecast_horizon
            over_time: 2          
            low_threhold: -5
            high_threhold: 5   
            col_def:
                col_list: *col_list
                datetime_index_column: 'datetime_number'
                group_column: 'instrument'
                group_rank_column: 'instrument_rank'
                target_column: 'label'
                time_column: 'time_idx'    
                future_covariate_col: ['dayofweek']   
                past_covariate_col: ['STD5','PRICE_SCOPE','TURNOVER_CLOSE', 'CORR5','RESI10']  
                static_covariate_col: ['instrument']    
    backtest:
       run_file: "./custom/trader/rqalpha/backtest.py"
       rqalpha:
          base: 
             start_date: "2021-05-06"
             end_date: "2021-05-30"
             benchmark: "000300.XSHG"
             accounts: 
                stock: 100000
          extra: 
             log_level: "verbose"
             context_vars:
                strategy_class: 
                   class: DayStrategy
                   module_path: trader.rqalpha.strategy_class.backtest_day      
                   config_path: "custom/config/workflow/backtest_day.yaml"
                   provider_uri: "/home/qdata/qlib_data/custom_cn_data"     
                strategy:
                   position_max_number: 3
                   single_buy_mount_percent: 20
                   keep_day_number: 3                   
          mod: 
             sys_analyser: 
                enabled: True
                plot: True
                report_save_path: "custom/data/trader/report"

            
        
            
